G++ = g++
FILES = main.cpp Continent/continent.cpp Country/country.cpp Earth/earth.cpp Human/human.cpp LifeCycle/lifecycle.cpp Sun/sun.cpp
EXE = Life 
DEL = rm
TXT = LifeCycleResult.txt

all:
	$(G++) $(FILES) -o $(EXE)
del:
	$(DEL) $(EXE)
delall:
	$(DEL) $(EXE) $(TXT)
